# This file was generated by GoReleaser. DO NOT EDIT.
cask "lemon-squeezy-cli" do
  version "0.3.4"

  on_macos do
    on_arm do
      sha256 "5b6505ec5152a824e12c2896802980dae78d97b1f9e2d256b82eab096ab2a0be"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "368ad2004de7ac03b406078b8d35bbbbfafb49ffc20fda6e305ca396d639f048"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c31229b90470c483f38cf934ad51288c965e0987f8f62a62e4b6c6dfa40600bc"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0fe5bacc98db4813ddffdffcda9f61e4f45898a496dfcb28efb30a05b2e2b7da"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lemon-squeezy-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/lemon-squeezy-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lsqueezy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lsqueezy"]
  end

  # No zap stanza required
end
