# This file was generated by GoReleaser. DO NOT EDIT.
cask "lemon-squeezy-cli" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "4884d8e0d08277eb7a63b5ed7310b6b65f45cc26bd75ad96d373a53cd3174eb7"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0254d0e3648294d0b30bd0110892483e1d94b50862b521441c6e1d45211b0bf9"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8aa7a5a11251cca8aaf8fe91dd2d6344fc8d68842fb012a39914da2503781a81"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cd03b2b9b8b73fbd9246765e9c689accedebe87aaf6af08608fd599cf37d2ad"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lemon-squeezy-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/lemon-squeezy-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lsqueezy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lsqueezy"]
  end

  # No zap stanza required

end
