# This file was generated by GoReleaser. DO NOT EDIT.
cask "lemon-squeezy-cli" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "54af529968c583ce159addb3ec0fd5e4e1664bf9cc069898031e0516bb4aa192"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9dc635033499bfcc4f4ab0abbd16e240d0ba2a2dbeb378a7dd1a175a31d033b3"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9046ae42ececd51817516b6f0fa1be7ff4b878594e093c11e9905a79959990d"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83c93329f2377c46a8d4c9d6484dd18a25b997343717c04067eec6566aa6746a"
      url "https://github.com/jjuanrivvera/lemon-squeezy-cli/releases/download/v#{version}/lemon-squeezy-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lemon-squeezy-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/lemon-squeezy-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lsqueezy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lsqueezy"]
  end

  # No zap stanza required

end
